# Generated by Django 3.1.7 on 2021-08-20 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prodOpr.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='product/', validators=[prodOpr.validations.validate_img])),
                ('price', models.FloatField(default=0.0, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
